name = "presentable_soup"
version = "2.0.0"
description = "Efficient querying, scraping, and parsing of HTML. Good for snapshot testing too!"

licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "presentable-soup" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
htmerl = ">= 0.2.0 and < 1.0.0"
houdini = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.3.2 and < 2.0.0"
